-- Superseded by 20260331103702_add_kiosk_payment_receipts.sql.
-- Production already applied the earlier migration, so this file must remain
-- a no-op to avoid replaying duplicate DDL on fresh environments.
