-- Superseded by 20260330123332_audit_triggers_all_tables.sql.
-- Production already applied the earlier migration, so this file must remain
-- a no-op to avoid replaying duplicate DDL on fresh environments.
