-- Superseded by 20260330092629_add_kiosk_contracts.sql and
-- 20260330103212_add_participant_verified_at_and_pending_admin_status.sql.
-- Production already applied the earlier migrations, so this file must remain
-- a no-op to avoid replaying duplicate DDL on fresh environments.
