-- Superseded by 20260330122835_kiosk_row_level_audit_triggers.sql.
-- Production already applied the earlier migration, so this file must remain
-- a no-op to avoid replaying duplicate DDL on fresh environments.
